<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="panel panel-default bg-success">
			<div class="panel-body">
				<img src="./Public/img/perfil.jpg" class="img-circle pull-left" alt="Avatar">
				
				<div class="pull-left" style="margin-left: 15px;">
					<strong class="font-16">Cadastro</strong><br />
				</div>
			</div>
			
			<!-- /list-group -->
		</div>
	</div>
	<div class="col-md-2"></div>
</div>