<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title><?php echo $this->titulo; ?></title>

<link rel="stylesheet" href="./Public/css/bootstrap.min.css">
<link rel="stylesheet" href="./Public/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="./Public/css/font-awesome.min.css">
<link rel="stylesheet" href="./Public/css/index.css">

</head>

<body>

	<?php echo $this->conteudo; ?>
	
	<script src="./Public/js/jquery-1.11.3.js"></script>
	<script src="./Public/js/login.js"></script>

</body>
</html>