<div class="row">
	<div class="col-md-12 col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-comment"></i> Chat
				<div class="pull-right">
					<a href='#' class="refresh"><i class="fa fa-refresh"></i> Refresh</a>
				</div>
			</div>
			<div class="panel-body">
				<div id="chatScroll">
					<ul class="chat">
						<li class="left"><span class="chat-img pull-left"> <img src="./Public/img/1.png" alt="Avatar">
						</span>
							<div class="chat-body">
								<div class="header">
									<strong class="primary-font">Fernanda</strong> <small class="pull-right"><i class="fa fa-clock-o"></i> 12 min</small>
								</div>
								<p>Os relat&oacute;rios da semana est&atilde;o prontos para serem consultados.</p>
							</div></li>
						<li class="right"><span class="chat-img pull-right"> <img src="./Public/img/4.png" alt="Avatar">
						</span>
							<div class="chat-body">
								<div class="header">
									<strong class="primary-font">Richard</strong> <small class="pull-right"><i class="fa fa-clock-o"></i> 22 min</small>
								</div>
								<p>Reuni&atilde;o da equipe foi adiada para as 14:30, todos os participantes est&atilde;o informados.</p>
							</div></li>
						<li class="left"><span class="chat-img pull-left"> <img src="./Public/img/5.png" alt="Avatar">
						</span>
							<div class="chat-body">
								<div class="header">
									<strong class="primary-font">Vanessa</strong> <small class="pull-right"><i class="fa fa-clock-o"></i> 24 min</small>
								</div>
								<p>Por favor, verificar os lan&ccedil;amentos do m&ecirc;s, se est&atilde;o todos corretos, pois ser&aacute; fechado hoje.</p>
							</div></li>
						<li class="right"><span class="chat-img pull-right"> <img src="./Public/img/1.png" alt="Avatar">
						</span>
							<div class="chat-body">
								<div class="header">
									<strong class="primary-font">Fernanda</strong> <small class="pull-right"><i class="fa fa-clock-o"></i> 28 min</small>
								</div>
								<p>Validar o &uacute;ltimo lan&ccedil;amento na data de 24/11/2015, valores n&atilde;o est&atilde;o coindizentes.</p>
							</div></li>
						<li class="left"><span class="chat-img pull-left"> <img src="./Public/img/4.png" alt="Avatar">
						</span>
							<div class="chat-body">
								<div class="header">
									<strong class="primary-font">Richard</strong> <small class="pull-right"><i class="fa fa-clock-o"></i> 36 min</small>
								</div>
								<p>Prezado, precisamos verificar um novo cadastro de categoria.</p>
							</div></li>
						</li>
					</ul>
				</div>
			</div>
			<div class="panel-footer">
				<div class="input-group">
					<input id="btn-input" type="text" class="form-control input-sm" placeholder="digite aqui..."> <span class="input-group-btn">
						<button class="btn btn-warning btn-sm" id="btn-chat">Enviar</button>
					</span>
				</div>
				<!-- /input-group -->
			</div>
		</div>
	</div>
</div>