<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Login</title>

<link rel="stylesheet" href="./Public/css/bootstrap.min.css">
<link rel="stylesheet" href="./Public/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="./Public/css/font-awesome.min.css">
<link rel="stylesheet" href="./Public/css/index.css">

</head>

<body>
	<div class="login-wrapper">
		<h2 class="fadeInUp animation-delay8">
			<span>Treinamento </span> <span id="sofbox">Softbo</span><img alt="Softbox" src="./Public/img/sofbox.png">
		</h2>
		<div class="login-widget animation-delay1">
			<div class="panel panel-default">
				<div class="panel-heading clearfix">
					<div class="pull-left">
						<i class="fa fa-lock fa-lg"></i> Login
					</div>
				</div>
				<div class="panel-body">
					<form method="post" class="form-login">
						<div class="form-group">
							<label>Usu&aacute;rio</label> <input type="text" name="usuario" placeholder="Usu&aacute;rio" class="form-control input-sm inDown animation-delay2">
						</div>
						<div class="form-group">
							<label>Senha</label> <input type="password" name="senha" placeholder="Senha" class="form-control input-sm inDown animation-delay4">
						</div>
						<div class="form-group">
							<label><input type="checkbox" class="chk-delete" /> <span class="inDown animation-delay4"></span>
							</label> Lembrar-me
						</div>

						<div class="seperator"></div>
						<div class="form-group">
							Esqueceu sua senha?<br /> Clique <a href="#">aqui</a> para resetar sua senha.
						</div>

						<hr />

						<button type="submit" class="btn btn-success btn-sm bounceIn animation-delay5 login-link pull-right">
							<i class="fa fa-sign-in"></i> Login
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>
</html>